### ISSUE TITLE
build does not work

### ISSUE THREAD

**Issue by jt3k** [jakoblind/react-parcel#1]
after run  `parcel build index.html` i get error

```
🚨  /private/tmp/paecel-react/index.js: Cannot read property 'start' of undefined
```

**Comment by jakoblind** [comment]
There is a bug in parcel that they currently work on fixing. In the mean time use this : 
parcel build index.html --no-minify

More info: https://github.com/parcel-bundler/parcel/issues/8#issuecomment-349422021
